# Site settings
title: Marvin Spahn
description: > # this means to ignore newlines until "baseurl:"
  3D Artist
url: https://git-maspa.github.io
#the base hostname & protocol for your site
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
    external:     false
  - name:         Archive
    url:          /archive
    external:     false
    external:     false
  - name:         Artstation
    url:          https://www.artstation.com/maspa
    external:     true

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]